weekly: silence an empty-range warning
A range is used in a (mutable) way which trips clippy
detection logic for empty ranges. This silences the following
warning:

```
error: this range is empty so it will yield no values

  --> src/weekly/mod.rs:61:30
   |
61 |           let mut last_range = Range {
   |  ______________________________^
62 | |             start: 0u32,
63 | |             end: 0u32,
64 | |         };
   | |_________^
```